---
- name: Setup VM with Docker, Nginx, and ReactJS
  hosts: all
  become: yes

  tasks:
      # Mise à jour du système
      - name: Update apt cache
        apt:
            update_cache: yes

      # Installation des paquets nécessaires
      - name: Install required packages
        apt:
            name:
                - apt-transport-https
                - ca-certificates
                - curl
                - gnupg-agent
                - software-properties-common
                - docker.io
                - nginx

      # Démarrer et activer Docker
      - name: Start and enable Docker
        systemd:
            name: docker
            enabled: yes
            state: started

      # Installer Node.js et npm
      - name: Install Node.js and npm
        apt:
            name:
                - nodejs
                - npm

      - name: Install Docker Compose
        apt:
            name: docker-compose
            state: present

      - name: Install Yarn globally using npm
        npm:
            name: yarn
            global: yes
