# .github/workflows/ci.yml
name: CI

on:
    push:
        branches:
            - main # adjust based on your default branch name
    pull_request:
        branches:
            - main # adjust based on your default branch name

jobs:
    build-and-test:
        runs-on:
            - vm-prod

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "14" # specify your Node.js version

            - name: Install dependencies
              run: npm install

            - name: Build project
              run: npm run build

            # - name: Lint project
            #   run: npm run lint
