name: Deploy to Azure VM

on:
    push:
        branches:
            - main # Adjust this based on your branch name

jobs:
    deploy:
        runs-on: vm-prod

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: SSH and deploy
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.AZURE_VM_IP }} # Azure VM IP address
                  username: ${{ secrets.AZURE_VM_USERNAME }} # Azure VM username
                  key: ${{ secrets.AZURE_VM_SSH_KEY }} # Azure VM SSH private key
                  script: |
                      cd /home/rui/delicias-da-celia
                      docker-compose down
                      docker-compose pull
                      docker-compose up -d
