# .github/workflows/ci.yml
name: CI

on:
    push:
        branches:
            - main # adjust based on your default branch name
    pull_request:
        branches:
            - main # adjust based on your default branch name

jobs:
    deploy:
        runs-on: [self-hosted, vm-prod] # This will target runners with the tag "vm-prod"

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: SSH and deploy
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.AZURE_VM_IP }} # Azure VM IP address
                  username: ${{ secrets.AZURE_VM_USERNAME }} # Azure VM username
                  key: ${{ secrets.AZURE_VM_SSH_KEY }} # Azure VM SSH private key
                  script: |
                      cd /home/rui/delicias-da-celia
                      docker-compose down
                      docker-compose pull
                      docker-compose up -d
