# .github/workflows/ci.yml
name: CI

on:
    push:
        branches:
            - main # adjust based on your default branch name
    pull_request:
        branches:
            - main # adjust based on your default branch name

jobs:
    deploy:
        runs-on: [self-hosted, vm-prod] # This will target runners with the tag "vm-prod"

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Build and push Docker image
              run: |
                  docker-compose build
                  docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
                  docker-compose push

            - name: SSH to Azure VM and deploy
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.AZURE_VM_IP }}
                  username: ${{ secrets.AZURE_VM_USERNAME }}
                  key: ${{ secrets.AZURE_VM_SSH_KEY }}
                  port: ${{ secrets.AZURE_VM_PORT }}
                  script: |
                      cd /home/{{ secrets.AZURE_VM_USERNAME }}/delicias-da-celia
                      docker-compose pull
                      docker-compose up -d
